### ISSUE TITLE
how shall we use it?

### ISSUE THREAD

**Issue by arpitprod** [appium-boneyard/javascript-workshop#2]
use this cli - ' VERBOSE=true grunt test:android:4.4'

> > Local Npm module "grunt-env" not found. Is it installed?
> > Local Npm module "grunt-simple-mocha" not found. Is it installed?
> > Local Npm module "grunt-concurrent" not found. Is it installed?
> > Local Npm module "grunt-contrib-jshint" not found. Is it installed?
> > Local Npm module "grunt-contrib-watch" not found. Is it installed?

Done, without errors.

where will we see test report

**Comment by imurchie** [comment]
Did you run `npm install`?
